name: pnpp_test

task_name: pnpp_test

shape_meta: &shape_meta
  obs:
    point_cloud:
      shape: [1024, 3]
      type: point_cloud
    imagin_robot:
      shape: [96, 7]
      type: point_cloud
    image:
      shape: [3, 84, 84]
      type: rgb
    agent_pos:
      shape: [6]
      type: low_dim
  action:
    shape: [8]

env_runner: null

dataset:
  _target_: diffusion_policy_3d.dataset.dexart_dataset.DexArtDataset
  zarr_path: data/pnpp_expert.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.0
  max_train_episodes: null
